"""Gravity forward modelling

This package includes classes and functions for the forward modelling of the
gravity field. The forward modelling is the computation of the gravitational
field generated by some known, usually simple, mass distribution.
"""
